[package]
name = "catalog-capture-plugin-adapter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["high-precision"]
high-precision = [
  "catalog-capture-core/high-precision",
  "catalog-capture-runtime-adapter/high-precision",
]

[dependencies]
anyhow.workspace = true
catalog-capture-core = { path = "../catalog-capture-core" }
catalog-capture-runtime-adapter = { path = "../catalog-capture-runtime-adapter" }
